## Numpy 基础运算1

In [3]:
import numpy as np
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)              # array([0, 1, 2, 3])
b

array([0, 1, 2, 3])

### numpy 的几种基本运算

上述代码中的 `a` 和 `b` 是两个属性为 array 也就是矩阵的变量，而且二者都是1行4列的矩阵， 其中b矩阵中的元素分别是从0到3。

In [7]:
c=a-b  # array([10, 19, 28, 37])
print(c)
c=a+b   # array([10, 21, 32, 43])
print(c)
c=a*b   # array([  0,  20,  60, 120])
print(c)

c=b**2  # array([0, 1, 4, 9])
print(c)

[10 19 28 37]
[10 21 32 43]
[  0  20  60 120]
[0 1 4 9]


### Numpy中具有很多的数学函数

Numpy三角函数等，当我们需要对矩阵中每一项元素进行函数运算时，可以很简便的调用它们（以sin函数为例）：

In [9]:
c=10*np.sin(a)  
# array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


### print函数修改进行逻辑判断：

In [10]:
print(b<3)  
# array([ True,  True,  True, False], dtype=bool)

[ True  True  True False]


上述运算均是建立在一维矩阵，即只有一行的矩阵上面的计算，如果我们想要对多行多维度的矩阵进行操作，需要对开始的脚本进行一些修改：

In [12]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))

print(a)
# array([[1, 1],
#       [0, 1]])

print(b)
# array([[0, 1],
#       [2, 3]])

print(b > 2)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[False False]
 [False  True]]


### numpy 两种矩阵乘法

此时构造出来的矩阵a和b便是2行2列的，其中 reshape 操作是对矩阵的形状进行重构， 其重构的形状便是括号中给出的数字。 稍显不同的是，Numpy中的矩阵乘法分为两种， 其一是前文中的对应元素相乘，其二是标准的矩阵乘法运算，即对应行乘对应列得到相应元素：

In [16]:
print(a)
print(b)

c_dot = np.dot(a,b)
# array([[2, 4],
#       [2, 3]])
print("========")
print(c_dot)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[2 4]
 [2 3]]


除此之外还有另外的一种关于`dot`的表示方法，即：

In [17]:
c_dot_2 = a.dot(b)
# array([[2, 4],
#       [2, 3]])

下面我们将重新定义一个脚本, 来看看关于 `sum()`, `min()`, `max()` 的使用：

In [18]:
import numpy as np
a=np.random.random((2,4))
print(a)
# array([[ 0.94692159,  0.20821798,  0.35339414,  0.2805278 ],
#       [ 0.04836775,  0.04023552,  0.44091941,  0.21665268]])

[[ 0.38281924  0.40654978  0.69744113  0.90707595]
 [ 0.40572074  0.652105    0.24226191  0.95931459]]


因为是随机生成数字, 所以你的结果可能会不一样. 在第二行中对a的操作是令a中生成一个2行4列的矩阵，且每一元素均是来自从0到1的随机数。 在这个随机生成的矩阵中，我们可以对元素进行求和以及寻找极值的操作，具体如下：

In [22]:
np.sum(a)   # 4.6532883360785817
np.min(a)   # 0.24226191007863129
np.max(a)   # 0.95931458707579575

0.95931458707579575

对应的便是对矩阵中所有元素进行求和，寻找最小值，寻找最大值的操作。 可以通过print()函数对相应值进行打印检验。

如果你需要对行或者列进行查找运算，就需要在上述代码中为 axis 进行赋值。 

当axis的值为0的时候，将会以列作为查找单元， 当axis的值为1的时候，将会以行作为查找单元。

为了更加清晰，在刚才的例子中我们继续进行查找：

In [23]:
print("a =",a)
# a = [[ 0.23651224  0.41900661  0.84869417  0.46456022]
# [ 0.60771087  0.9043845   0.36603285  0.55746074]]

print("sum =",np.sum(a,axis=1))
# sum = [ 1.96877324  2.43558896]

print("min =",np.min(a,axis=0))
# min = [ 0.23651224  0.41900661  0.36603285  0.46456022]

print("max =",np.max(a,axis=1))
# max = [ 0.84869417  0.9043845 ]

a = [[ 0.38281924  0.40654978  0.69744113  0.90707595]
 [ 0.40572074  0.652105    0.24226191  0.95931459]]
sum = [ 2.3938861   2.25940224]
min = [ 0.38281924  0.40654978  0.24226191  0.90707595]
max = [ 0.90707595  0.95931459]
