numpy copy & deep copy

## = 的赋值方式会带有关联性

In [1]:
import numpy as np

a = np.arange(4)
# array([0, 1, 2, 3])

b = a
c = a
d = b

改变`a`的第一个值，`b`、`c`、`d`的第一个值也会同时改变。

In [2]:
a[0] = 11
print(a)
# array([11,  1,  2,  3])

[11  1  2  3]


确认`b`、`c`、`d`是否与`a`相同

In [3]:
b is a  # True
c is a  # True
d is a  # True

True

## copy() 的赋值方式没有关联性

In [4]:
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3])

[11  1  2  3]
[11  1  2 44]
[11  1  2  3]
